# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 21:50
from __future__ import unicode_literals

import Phoenix.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_dig', models.CharField(max_length=200)),
                ('dominio', models.CharField(max_length=200)),
                ('endservidor', models.CharField(max_length=200)),
                ('gadmin', models.CharField(max_length=200)),
                ('ou', models.CharField(max_length=200)),
                ('filter', models.TextField(verbose_name='Filtro')),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=120, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('logo', models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Logotipo')),
                ('slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('num_serie', models.CharField(max_length=200, verbose_name='Número de Série')),
                ('ip', models.CharField(max_length=20, verbose_name='Endereço IP')),
                ('mac', models.CharField(max_length=20, verbose_name='Endereço MAC')),
                ('licenca', models.CharField(max_length=50, null=True, verbose_name='Chave de Licenciamento')),
                ('tipo', models.CharField(choices=[('f', 'Fisíco'), ('s', 'Virtual')], max_length=50, verbose_name='Tipo de Equipamento')),
                ('monitorado', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=50, verbose_name='Necessita Monitoramento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=200, null=True, verbose_name='Endereço de Acesso')),
                ('licenca', models.CharField(max_length=50, null=True, verbose_name='Chave de Licenciamento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='id_marca',
            field=models.ForeignKey(on_delete=Phoenix.core.models.marca, to='core.marca'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='id_modelo',
            field=models.ForeignKey(on_delete=Phoenix.core.models.modelo, to='core.modelo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='id_sala',
            field=models.ForeignKey(on_delete=Phoenix.core.models.sala, to='core.sala'),
        ),
    ]
