# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipamento_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='sistema_operacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do SO')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('licenca', models.CharField(max_length=50, null=True, verbose_name='Chave de Licenciamento')),
                ('arquitetura', models.CharField(choices=[('32', '32 bits'), ('64', '64 bits')], max_length=60, verbose_name='Arquitetura')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='sistema_operacional_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do Software')),
                ('descricao', models.CharField(max_length=90, verbose_name='Descrição')),
                ('licenca', models.CharField(max_length=50, null=True, verbose_name='Chave de Licenciamento')),
                ('arquitetura', models.CharField(choices=[('32', '32 bits'), ('64', '64 bits')], max_length=60, verbose_name='Arquitetura')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='software_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='software_equipamento',
            name='id_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
        migrations.AddField(
            model_name='software_equipamento',
            name='id_software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.software'),
        ),
        migrations.AddField(
            model_name='sistema_operacional_equipamento',
            name='id_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
        migrations.AddField(
            model_name='sistema_operacional_equipamento',
            name='id_sistema_operacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistema_operacional'),
        ),
    ]
