# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181129_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='servico_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='licenca',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='id_equipamento',
        ),
        migrations.AddField(
            model_name='servico_equipamento',
            name='id_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
        migrations.AddField(
            model_name='servico_equipamento',
            name='id_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
    ]
