# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181130_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sistema_operacional',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='software',
            name='descricao',
            field=models.CharField(max_length=90, verbose_name='Descrição'),
        ),
    ]
