# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181130_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizacao',
            name='id_equipamento',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
            preserve_default=False,
        ),
    ]
