# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_virtualizacao_arquitetura'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizacao',
            name='ip',
            field=models.CharField(default=12, max_length=20, verbose_name='Endereço IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualizacao',
            name='mac',
            field=models.CharField(default=3, max_length=20, verbose_name='Endereço MAC'),
            preserve_default=False,
        ),
    ]
