# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_virtualizacao_arquitetura'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtualizacao_equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='virtualizacao',
            name='id_equipamento',
        ),
        migrations.AddField(
            model_name='virtualizacao_equipamento',
            name='id_virtualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.virtualizacao'),
        ),
    ]
